import { Inter } from "next/font/google";
import "./Component/Nav.css"
import "./Home/home.css"
import "./About/About.css"
import "./Contact/Contact.css"
import "./Skills/Skills.css"
import "./Component/Card.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
